In [1]:
import os

In [2]:
print(os.getcwd())

C:\Users\thoma

In [3]:
os.chdir(r"C:\Users\thoma\Desktop\myJupyterNotebooks")

In [4]:
print(os.getcdw())

AttributeError: module 'os' has no attribute 'getcdw'

In [5]:
os.getcwd()

'C:\\Users\\thoma\\Desktop\\myJupyterNotebooks'

In [6]:
import pandas as pd #import the pandas 'toolbox'

In [7]:
data = pd.read_csv('Realestate.csv') #read in the data file

In [8]:
data.head() #display the first bit of the data to see what it contains

,No,transaction,houseAge,distanceToNearestMRTstation,numberOfConvenienceStores,latitude,longitude,housePriceOfUnitArea
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,NaN
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [9]:
data["houseAge"] = (data["houseAge"] - data["houseAge"].min()) / (data["houseAge"].max() - data["houseAge"].min()) #normalizes the houseAge data using the formula to convert values into a 0-1 scale

In [10]:
data.head()

,No,transaction,houseAge,distanceToNearestMRTstation,numberOfConvenienceStores,latitude,longitude,housePriceOfUnitArea
0,1,2012.917,0.730594,84.87882,10,24.98298,121.54024,NaN
1,2,2012.917,0.445205,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,0.303653,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,0.303653,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,0.114155,390.56840,5,24.97937,121.54245,43.1

In [11]:
data

,No,transaction,houseAge,distanceToNearestMRTstation,numberOfConvenienceStores,latitude,longitude,housePriceOfUnitArea
0,1,2012.917,0.730594,84.87882,10,24.98298,121.54024,NaN
1,2,2012.917,0.445205,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,0.303653,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,0.303653,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,0.114155,390.56840,5,24.97937,121.54245,43.1
...,...,...,...,...,...,...,...,...
413,410,2013.000,0.312785,4082.01500,0,24.94155,121.50381,15.4
414,411,2012.667,0.127854,90.45606,9,24.97433,121.54310,50.0
415,412,2013.250,0.429224,390.96960,7,24.97923,121.53986,40.6
416,413,2013.000,0.184932,104.81010,5,24.96674,121.54067,52.5
417,414,2013.500,0.148402,90.45606,9,24.97433,121.54310,63.9

In [12]:
data.to_csv("Realestate_transformed.csv", index=False) #created a new csv file for the updated data and saved the first change to it

In [13]:
data["houseAgeStandardized"] = data["houseAge"] #made a new column for the standardized houseAge data

In [14]:
data.head()

,No,transaction,houseAge,distanceToNearestMRTstation,numberOfConvenienceStores,latitude,longitude,housePriceOfUnitArea,houseAgeStandardized
0,1,2012.917,0.730594,84.87882,10,24.98298,121.54024,NaN,0.730594
1,2,2012.917,0.445205,306.59470,9,24.98034,121.53951,42.2,0.445205
2,3,2013.583,0.303653,561.98450,5,24.98746,121.54391,47.3,0.303653
3,4,2013.500,0.303653,561.98450,5,24.98746,121.54391,54.8,0.303653
4,5,2012.833,0.114155,390.56840,5,24.97937,121.54245,43.1,0.114155

In [15]:
data.drop("numberOfConvenienceStores", axis=1, inplace=True) #removes the numberOfConvenienceStores column

In [16]:
data.columns #verify that the column was removed

Index(['No', 'transaction', 'houseAge', 'distanceToNearestMRTstation',
       'latitude', 'longitude', 'housePriceOfUnitArea',
       'houseAgeStandardized'],
      dtype='object')

In [17]:
data.rename(columns={"transaction": 'transactionDate'}, inplace=True) #renamed the column

In [18]:
data.columns #verify that the column name changed

Index(['No', 'transactionDate', 'houseAge', 'distanceToNearestMRTstation',
       'latitude', 'longitude', 'housePriceOfUnitArea',
       'houseAgeStandardized'],
      dtype='object')

In [19]:
data.loc[0:10] #use .loc[] to list the rows numbered 0-10 (total of 11 rows)

,No,transactionDate,houseAge,distanceToNearestMRTstation,latitude,longitude,housePriceOfUnitArea,houseAgeStandardized
0,1,2012.917,0.730594,84.87882,24.98298,121.54024,NaN,0.730594
1,2,2012.917,0.445205,306.59470,24.98034,121.53951,42.2,0.445205
2,3,2013.583,0.303653,561.98450,24.98746,121.54391,47.3,0.303653
3,4,2013.500,0.303653,561.98450,24.98746,121.54391,54.8,0.303653
4,5,2012.833,0.114155,390.56840,24.97937,121.54245,43.1,0.114155
5,6,2012.667,0.162100,2175.03000,24.96305,121.51254,32.1,0.162100
6,7,2012.667,0.787671,623.47310,24.97933,121.53642,40.3,0.787671
7,8,2013.417,0.463470,287.60250,24.98042,121.54228,46.7,0.463470
8,9,2013.500,0.723744,5512.03800,24.95095,121.48458,18.8,0.723744
9,10,2013.417,0.408676,1783.18000,24.96731,121.51486,22.1,0.408676
10,11,2013.083,0.794521,405.21340,24.97349,121.53372,41.4,0.794521

In [20]:
data.iloc[:10] #use .iloc[] to list the rows with integer values 0-9 (total of 10 rows)

,No,transactionDate,houseAge,distanceToNearestMRTstation,latitude,longitude,housePriceOfUnitArea,houseAgeStandardized
0,1,2012.917,0.730594,84.87882,24.98298,121.54024,NaN,0.730594
1,2,2012.917,0.445205,306.59470,24.98034,121.53951,42.2,0.445205
2,3,2013.583,0.303653,561.98450,24.98746,121.54391,47.3,0.303653
3,4,2013.500,0.303653,561.98450,24.98746,121.54391,54.8,0.303653
4,5,2012.833,0.114155,390.56840,24.97937,121.54245,43.1,0.114155
5,6,2012.667,0.162100,2175.03000,24.96305,121.51254,32.1,0.162100
6,7,2012.667,0.787671,623.47310,24.97933,121.53642,40.3,0.787671
7,8,2013.417,0.463470,287.60250,24.98042,121.54228,46.7,0.463470
8,9,2013.500,0.723744,5512.03800,24.95095,121.48458,18.8,0.723744
9,10,2013.417,0.408676,1783.18000,24.96731,121.51486,22.1,0.408676

In [21]:
data.duplicate().sum() #misspelled "duplicated"

AttributeError: 'DataFrame' object has no attribute 'duplicate'

In [22]:
data.duplicated().sum() #search for duplicated rows; the result tells me that there are 4 duplicate rows

np.int64(4)

In [23]:
data.drop_duplicates(inplace=True) #remove duplicated rows

In [24]:
data.duplicated().sum() #verify that the duplicates have been removed

np.int64(0)

In [25]:
data.isna().sum() #search for data that is missing (not a number); results show that there are 3 missing values in housePriceOfUnitArea

No                             0
transactionDate                0
houseAge                       0
distanceToNearestMRTstation    0
latitude                       0
longitude                      0
housePriceOfUnitArea           3
houseAgeStandardized           0
dtype: int64

In [26]:
data.fillna(data.mean(numeric_only=True), inplace=True) #fill missing values with the column mean value

In [27]:
data.isna().sum() #verify that there is no missing data anymore

No                             0
transactionDate                0
houseAge                       0
distanceToNearestMRTstation    0
latitude                       0
longitude                      0
housePriceOfUnitArea           0
houseAgeStandardized           0
dtype: int64

In [28]:
data.to_csv("Realestate_transformed.csv", index=False) #save changes to the new csv file

In [29]:
print(os.getcwd())

C:\Users\thoma\Desktop\myJupyterNotebooks